name: C/C++ CI

on: [push]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    #- name: configure
    #  run: ./configure
    - name: Create Build Directory
      run: mkdir build
    - name: Configure CMake
      run: cd build && cmake ..
    - name: Build
      working-directory: /build/
      run: make
    - name: Make Check
      working-directory: /build/
      run: make check
      run: make distcheck
